services:
  traefik:
    image: "traefik:3"
    command:
      - "--ping=true"
      - "--api.dashboard=false"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--accesslog.filepath=/data/access.log"
      # entrypoints
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--log.level=DEBUG"
    container_name: "traefik"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      traefik.enable: "true"
      traefik.http.routers.dashboard.rule: "Host(`${HOST}`)"
      traefik.http.routers.dashboard.entrypoints: "traefik"
      traefik.http.routers.dashboard.service: "api@internal"
      traefik.http.routers.dashboard.middlewares: "auth"
      # Define basic auth middleware
      traefik.http.middlewares.auth.basicauth.users: "admin:$$2y$$10$$X7rFwqB45ACe3qXNwCyQiOGEZ/11SbWoWPdfBTbGgX8XFOO9VCHEe" # admin:admin
    ports:
      - "80:80"
      - "443:443"
    networks:
      - djangonetwork

  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    env_file:
      - .env
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - djangonetwork

  web:
    image: antijob/neuro-parser:${NEURO_PARSER_VERSION}
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        PDM_DEPENDENCY_GROUPS: "test ml"
    command: /bin/bash -c ./docker/web/entrypoint-prod.sh
    env_file:
      - .env
    environment:
      DEBUG: "${DEBUG}"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REPLICATE_API_TOKEN: ${REPLICATE_API_TOKEN}
      API_RPS: ${API_RPS}
    volumes:
      - /root/models:/code/models
      - "staticfiles-data:/code/public/static"
      - "thelethon:/code/.telethon"
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    labels:
      traefik.enable: "true"
      traefik.http.routers.django.rule: "Host(`${HOST}`) && !PathPrefix(`/static/`) && !PathPrefix(`/flower`)"
      traefik.http.routers.django.entrypoints: "https"
      traefik.http.routers.django.tls: "true"
      traefik.http.services.django.loadbalancer.server.port: "8000"
    networks:
      - djangonetwork

  celery:
    image: antijob/neuro-parser:${NEURO_PARSER_VERSION}
    command: /bin/bash -c "./docker/celery/entrypoint.sh"
    env_file:
      - .env
    environment:
      REPLICATE_API_TOKEN: ${REPLICATE_API_TOKEN}
    volumes:
      - /root/models:/code/models
      - "thelethon:/code/.telethon"
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - djangonetwork

  bot:
    image: antijob/neuro-parser:${NEURO_PARSER_VERSION}
    command: /bin/bash -c "./docker/bot/entrypoint.sh"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - redis
      - web
    networks:
      - djangonetwork

  flower:
    image: mher/flower
    command: celery flower --url_prefix=flower
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      FLOWER_BASIC_AUTH: ${FLOWER_USER}:${FLOWER_PASSWORD}
    expose:
      - "5555"
    restart: always
    depends_on:
      - redis
      - web
      - celery
    labels:
      traefik.enable: "true"
      traefik.http.routers.flower.rule: "Host(`${HOST}`) && PathPrefix(`/flower`)"
      traefik.http.routers.flower.entrypoints: "https"
      traefik.http.routers.flower.tls: "true"
      traefik.http.routers.flower.priority: 1000
      traefik.http.routers.flower.middlewares: "flower-slash"
      traefik.http.middlewares.flower-slash.redirectregex.regex: "^(https?://[^/]+/flower)$"
      traefik.http.middlewares.flower-slash.redirectregex.replacement: "$${1}/"
      traefik.http.services.flower.loadbalancer.server.port: "5555"
    networks:
      - djangonetwork

  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - djangonetwork

  nginx:
    image: nginx:1.23
    restart: unless-stopped
    volumes:
      - staticfiles-data:/usr/share/nginx/html/static:ro
    depends_on:
      - web
    networks:
      - djangonetwork
    labels:
      traefik.enable: "true"
      traefik.http.routers.staticfiles.rule: "Host(`${HOST}`) && PathPrefix(`/static/`)"
      traefik.http.routers.staticfiles.entrypoints: "https"
      traefik.http.routers.staticfiles.tls: "true"
      traefik.http.services.staticfiles.loadbalancer.server.port: "80"

volumes:
  staticfiles-data:
  postgres_data_prod:
  thelethon:

networks:
  djangonetwork:
    driver: bridge
