services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/traefik.toml:ro"
      - "./acme.json:/acme.json"
    networks:
      - djangonetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${HOST}`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
  db:
    image: postgres:13.4-alpine
    volumes:
      - ~/.parser/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=md5
    env_file:
      - .env
    networks:
      - djangonetwork
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - djangonetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${HOST}`) && PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=8000"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - djangonetwork
  celery:
    build: .
    command: celery -A server worker --loglevel=info
    restart: always
    depends_on:
      - redis
    networks:
      - djangonetwork
networks:
  djangonetwork:
    driver: bridge
