# Generated by Django 2.2.5 on 2020-02-16 02:51

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_add_verbose_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('public', models.BooleanField(default=False, verbose_name='Публичная кампания')),
                ('form_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Форма в JSON')),
                ('slug', models.SlugField(unique=True, verbose_name='Название в URL')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор кампании')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
            },
        ),
        migrations.CreateModel(
            name='UserIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(0, 'Не обработана'), (1, 'Обработана и отклонена'), (2, 'Обработана и принята')], default=0, verbose_name='Статус')),
                ('public', models.BooleanField(default=False, verbose_name='Публичная заявка')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('region', models.CharField(choices=[('RU', 'Россия'), ('RU-AMU', 'Амурская область'), ('RU-ARK', 'Архангельская область'), ('RU-AST', 'Астраханская область'), ('RU-BEL', 'Белгородская область'), ('RU-BRY', 'Брянская область'), ('RU-VLA', 'Владимирская область'), ('RU-VGG', 'Волгоградская область'), ('RU-VLG', 'Вологодская область'), ('RU-VOR', 'Воронежская область'), ('RU-IVA', 'Ивановская область'), ('RU-IRK', 'Иркутская область'), ('RU-KGD', 'Калининградская область'), ('RU-KLU', 'Калужская область'), ('RU-KEM', 'Кемеровская область'), ('RU-KIR', 'Кировская область'), ('RU-KOS', 'Костромская область'), ('RU-KGN', 'Курганская область'), ('RU-KRS', 'Курская область'), ('RU-LEN', 'Ленинградская область'), ('RU-LIP', 'Липецкая область'), ('RU-MAG', 'Магаданская область'), ('RU-MOS', 'Московская область'), ('RU-MUR', 'Мурманская область'), ('RU-NIZ', 'Нижегородская область'), ('RU-NGR', 'Новгородская область'), ('RU-NVS', 'Новосибирская область'), ('RU-OMS', 'Омская область'), ('RU-ORE', 'Оренбургская область'), ('RU-ORL', 'Орловская область'), ('RU-PNZ', 'Пензенская область'), ('RU-PSK', 'Псковская область'), ('RU-ROS', 'Ростовская область'), ('RU-RYA', 'Рязанская область'), ('RU-SAM', 'Самарская область'), ('RU-SAR', 'Саратовская область'), ('RU-SAK', 'Сахалинская область'), ('RU-SVE', 'Свердловская область'), ('RU-SMO', 'Смоленская область'), ('RU-TAM', 'Тамбовская область'), ('RU-TVE', 'Тверская область'), ('RU-TOM', 'Томская область'), ('RU-TUL', 'Тульская область'), ('RU-TYU', 'Тюменская область'), ('RU-ULY', 'Ульяновская область'), ('RU-CHE', 'Челябинская область'), ('RU-YAR', 'Ярославская область'), ('RU-AD', 'Адыгея'), ('RU-BA', 'Башкортостан'), ('RU-BU', 'Бурятия'), ('RU-DA', 'Дагестан'), ('RU-IN', 'Ингушетия'), ('RU-KB', 'Кабардино-Балкария'), ('RU-KL', 'Калмыкия'), ('RU-KC', 'Карачаево-Черкесия'), ('RU-KR', 'Карелия'), ('RU-ME', 'Марий Эл'), ('RU-MO', 'Мордовия'), ('RU-AL', 'Республика Алтай'), ('RU-KO', 'Республика Коми'), ('RU-SA', 'Якутия'), ('RU-SE', 'Северная Осетия'), ('RU-TA', 'Татарстан'), ('RU-TY', 'Тыва'), ('RU-UD', 'Удмуртия'), ('RU-KK', 'Хакасия'), ('RU-CE', 'Чечня'), ('RU-CU', 'Чувашия'), ('RU-ALT', 'Алтайский край'), ('RU-ZAB', 'Забайкальский край'), ('RU-KAM', 'Камчатский край'), ('RU-KDA', 'Краснодарский край'), ('RU-KYA', 'Красноярский край'), ('RU-PER', 'Пермский край'), ('RU-PRI', 'Приморский край'), ('RU-STA', 'Ставропольский край'), ('RU-KHA', 'Хабаровский край'), ('RU-NEN', 'Ненецкий автономный округ'), ('RU-KHM', 'Ханты-Мансийский автономный округ — Югра'), ('RU-CHU', 'Чукотский автономный округ'), ('RU-YAN', 'Ямало-Ненецкий автономный округ'), ('RU-SPE', 'Санкт-Петербург'), ('RU-MOW', 'Москва'), ('RU-YEV', 'Еврейская автономная область'), ('UA-43', 'Автономная Республика Крым'), ('UA-40', 'Севастополь')], default='RU', max_length=16, verbose_name='Регион')),
                ('incident_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Вид ограничения')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество ограничений')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=32, null=True), blank=True, null=True, size=None)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, default='', null=True), blank=True, null=True, size=None)),
                ('public_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Публичное название')),
                ('public_description', models.TextField(blank=True, null=True, verbose_name='Публичное описание')),
                ('public_applicant_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Публичное имя заявителя')),
                ('form_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Данные из формы')),
                ('email', models.EmailField(max_length=254)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, назначенный на заявку')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents', to='core.Campaign')),
                ('public_organization', models.ManyToManyField(blank=True, to='users.Organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
        migrations.CreateModel(
            name='MediaIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(0, 'Не обработана'), (1, 'Обработана и отклонена'), (2, 'Обработана и принята')], default=0, verbose_name='Статус')),
                ('public', models.BooleanField(default=False, verbose_name='Публичная заявка')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('region', models.CharField(choices=[('RU', 'Россия'), ('RU-AMU', 'Амурская область'), ('RU-ARK', 'Архангельская область'), ('RU-AST', 'Астраханская область'), ('RU-BEL', 'Белгородская область'), ('RU-BRY', 'Брянская область'), ('RU-VLA', 'Владимирская область'), ('RU-VGG', 'Волгоградская область'), ('RU-VLG', 'Вологодская область'), ('RU-VOR', 'Воронежская область'), ('RU-IVA', 'Ивановская область'), ('RU-IRK', 'Иркутская область'), ('RU-KGD', 'Калининградская область'), ('RU-KLU', 'Калужская область'), ('RU-KEM', 'Кемеровская область'), ('RU-KIR', 'Кировская область'), ('RU-KOS', 'Костромская область'), ('RU-KGN', 'Курганская область'), ('RU-KRS', 'Курская область'), ('RU-LEN', 'Ленинградская область'), ('RU-LIP', 'Липецкая область'), ('RU-MAG', 'Магаданская область'), ('RU-MOS', 'Московская область'), ('RU-MUR', 'Мурманская область'), ('RU-NIZ', 'Нижегородская область'), ('RU-NGR', 'Новгородская область'), ('RU-NVS', 'Новосибирская область'), ('RU-OMS', 'Омская область'), ('RU-ORE', 'Оренбургская область'), ('RU-ORL', 'Орловская область'), ('RU-PNZ', 'Пензенская область'), ('RU-PSK', 'Псковская область'), ('RU-ROS', 'Ростовская область'), ('RU-RYA', 'Рязанская область'), ('RU-SAM', 'Самарская область'), ('RU-SAR', 'Саратовская область'), ('RU-SAK', 'Сахалинская область'), ('RU-SVE', 'Свердловская область'), ('RU-SMO', 'Смоленская область'), ('RU-TAM', 'Тамбовская область'), ('RU-TVE', 'Тверская область'), ('RU-TOM', 'Томская область'), ('RU-TUL', 'Тульская область'), ('RU-TYU', 'Тюменская область'), ('RU-ULY', 'Ульяновская область'), ('RU-CHE', 'Челябинская область'), ('RU-YAR', 'Ярославская область'), ('RU-AD', 'Адыгея'), ('RU-BA', 'Башкортостан'), ('RU-BU', 'Бурятия'), ('RU-DA', 'Дагестан'), ('RU-IN', 'Ингушетия'), ('RU-KB', 'Кабардино-Балкария'), ('RU-KL', 'Калмыкия'), ('RU-KC', 'Карачаево-Черкесия'), ('RU-KR', 'Карелия'), ('RU-ME', 'Марий Эл'), ('RU-MO', 'Мордовия'), ('RU-AL', 'Республика Алтай'), ('RU-KO', 'Республика Коми'), ('RU-SA', 'Якутия'), ('RU-SE', 'Северная Осетия'), ('RU-TA', 'Татарстан'), ('RU-TY', 'Тыва'), ('RU-UD', 'Удмуртия'), ('RU-KK', 'Хакасия'), ('RU-CE', 'Чечня'), ('RU-CU', 'Чувашия'), ('RU-ALT', 'Алтайский край'), ('RU-ZAB', 'Забайкальский край'), ('RU-KAM', 'Камчатский край'), ('RU-KDA', 'Краснодарский край'), ('RU-KYA', 'Красноярский край'), ('RU-PER', 'Пермский край'), ('RU-PRI', 'Приморский край'), ('RU-STA', 'Ставропольский край'), ('RU-KHA', 'Хабаровский край'), ('RU-NEN', 'Ненецкий автономный округ'), ('RU-KHM', 'Ханты-Мансийский автономный округ — Югра'), ('RU-CHU', 'Чукотский автономный округ'), ('RU-YAN', 'Ямало-Ненецкий автономный округ'), ('RU-SPE', 'Санкт-Петербург'), ('RU-MOW', 'Москва'), ('RU-YEV', 'Еврейская автономная область'), ('UA-43', 'Автономная Республика Крым'), ('UA-40', 'Севастополь')], default='RU', max_length=16, verbose_name='Регион')),
                ('incident_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Вид ограничения')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество ограничений')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=32, null=True), blank=True, null=True, size=None)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, default='', null=True), blank=True, null=True, size=None)),
                ('public_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Публичное название')),
                ('public_description', models.TextField(blank=True, null=True, verbose_name='Публичное описание')),
                ('public_applicant_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Публичное имя заявителя')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, назначенный на заявку')),
                ('public_organization', models.ManyToManyField(blank=True, to='users.Organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Инцидент из СМИ',
                'verbose_name_plural': 'Инциденты из СМИ',
            },
        ),
    ]
