# Generated by Django 3.2.21 on 2023-11-05 19:48

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('url', models.TextField(blank=True, default='', primary_key=True, serialize=False, verbose_name='URL')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Текст')),
                ('is_downloaded', models.BooleanField(default=False, verbose_name='Скачана')),
                ('is_parsed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('is_incident_created', models.BooleanField(default=False, verbose_name='Инцидент создан')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='Дубликат')),
                ('rate', models.JSONField(default=dict, verbose_name='Оценка релевантности')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Cтатья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.CharField(max_length=100, null=True)),
                ('treshold', models.FloatField(default=1, verbose_name='Treshold для модели')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название модели')),
                ('chat_gpt_prompt', models.TextField(blank=True, null=True, verbose_name='Chat-GPR промпт')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('should_sent_to_bot', models.BooleanField(default=True, verbose_name='Показывать в боте')),
            ],
            options={
                'verbose_name': 'Тип инцидента',
                'verbose_name_plural': 'Типы инцидентов',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True, verbose_name='URL списка новостей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('region', models.CharField(choices=[('RU', 'Россия'), ('RU-AMU', 'Амурская область'), ('RU-ARK', 'Архангельская область'), ('RU-AST', 'Астраханская область'), ('RU-BEL', 'Белгородская область'), ('RU-BRY', 'Брянская область'), ('RU-VLA', 'Владимирская область'), ('RU-VGG', 'Волгоградская область'), ('RU-VLG', 'Вологодская область'), ('RU-VOR', 'Воронежская область'), ('RU-IVA', 'Ивановская область'), ('RU-IRK', 'Иркутская область'), ('RU-KGD', 'Калининградская область'), ('RU-KLU', 'Калужская область'), ('RU-KEM', 'Кемеровская область'), ('RU-KIR', 'Кировская область'), ('RU-KOS', 'Костромская область'), ('RU-KGN', 'Курганская область'), ('RU-KRS', 'Курская область'), ('RU-LEN', 'Ленинградская область'), ('RU-LIP', 'Липецкая область'), ('RU-MAG', 'Магаданская область'), ('RU-MOS', 'Московская область'), ('RU-MUR', 'Мурманская область'), ('RU-NIZ', 'Нижегородская область'), ('RU-NGR', 'Новгородская область'), ('RU-NVS', 'Новосибирская область'), ('RU-OMS', 'Омская область'), ('RU-ORE', 'Оренбургская область'), ('RU-ORL', 'Орловская область'), ('RU-PNZ', 'Пензенская область'), ('RU-PSK', 'Псковская область'), ('RU-ROS', 'Ростовская область'), ('RU-RYA', 'Рязанская область'), ('RU-SAM', 'Самарская область'), ('RU-SAR', 'Саратовская область'), ('RU-SAK', 'Сахалинская область'), ('RU-SVE', 'Свердловская область'), ('RU-SMO', 'Смоленская область'), ('RU-TAM', 'Тамбовская область'), ('RU-TVE', 'Тверская область'), ('RU-TOM', 'Томская область'), ('RU-TUL', 'Тульская область'), ('RU-TYU', 'Тюменская область'), ('RU-ULY', 'Ульяновская область'), ('RU-CHE', 'Челябинская область'), ('RU-YAR', 'Ярославская область'), ('RU-AD', 'Республика Адыгея'), ('RU-BA', 'Республика Башкортостан'), ('RU-BU', 'Республика Бурятия'), ('RU-DA', 'Республика Дагестан'), ('RU-IN', 'Республика Ингушетия'), ('RU-KB', 'Кабардино-Балкарская Республика'), ('RU-KL', 'Республика Калмыкия'), ('RU-KC', 'Карачаево-Черкесская Республика'), ('RU-KR', 'Республика Карелия'), ('UA-43', 'Республика Крым'), ('RU-ME', 'Республика Марий Эл'), ('RU-MO', 'Республика Мордовия'), ('RU-AL', 'Республика Алтай'), ('RU-KO', 'Республика Коми'), ('RU-SA', 'Республика Саха (Якутия)'), ('RU-SE', 'Республика Северная Осетия — Алания'), ('RU-TA', 'Республика Татарстан'), ('RU-TY', 'Республика Тыва'), ('RU-UD', 'Удмуртская Республика'), ('RU-KK', 'Республика Хакасия'), ('RU-CE', 'Чеченская Республика'), ('RU-CU', 'Чувашская Республика'), ('RU-ALT', 'Алтайский край'), ('RU-ZAB', 'Забайкальский край'), ('RU-KAM', 'Камчатский край'), ('RU-KDA', 'Краснодарский край'), ('RU-KYA', 'Красноярский край'), ('RU-PER', 'Пермский край'), ('RU-PRI', 'Приморский край'), ('RU-STA', 'Ставропольский край'), ('RU-KHA', 'Хабаровский край'), ('RU-NEN', 'Ненецкий автономный округ'), ('RU-KHM', 'Ханты-Мансийский автономный округ — Югра'), ('RU-CHU', 'Чукотский автономный округ'), ('RU-YAN', 'Ямало-Ненецкий автономный округ'), ('RU-YEV', 'Еврейская автономная область'), ('RU-SPE', 'Санкт-Петербург'), ('RU-MOW', 'Москва'), ('UA-40', 'Севастополь')], default='RU', max_length=6, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='MediaIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(0, 'Не обработан'), (1, 'Отклонен'), (2, 'Принят'), (3, 'Коммуникации'), (4, 'В работе'), (5, 'Выполнен'), (6, 'Удален')], default=0, verbose_name='Статус')),
                ('create_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('region', models.CharField(choices=[('RU', 'Россия'), ('RU-AMU', 'Амурская область'), ('RU-ARK', 'Архангельская область'), ('RU-AST', 'Астраханская область'), ('RU-BEL', 'Белгородская область'), ('RU-BRY', 'Брянская область'), ('RU-VLA', 'Владимирская область'), ('RU-VGG', 'Волгоградская область'), ('RU-VLG', 'Вологодская область'), ('RU-VOR', 'Воронежская область'), ('RU-IVA', 'Ивановская область'), ('RU-IRK', 'Иркутская область'), ('RU-KGD', 'Калининградская область'), ('RU-KLU', 'Калужская область'), ('RU-KEM', 'Кемеровская область'), ('RU-KIR', 'Кировская область'), ('RU-KOS', 'Костромская область'), ('RU-KGN', 'Курганская область'), ('RU-KRS', 'Курская область'), ('RU-LEN', 'Ленинградская область'), ('RU-LIP', 'Липецкая область'), ('RU-MAG', 'Магаданская область'), ('RU-MOS', 'Московская область'), ('RU-MUR', 'Мурманская область'), ('RU-NIZ', 'Нижегородская область'), ('RU-NGR', 'Новгородская область'), ('RU-NVS', 'Новосибирская область'), ('RU-OMS', 'Омская область'), ('RU-ORE', 'Оренбургская область'), ('RU-ORL', 'Орловская область'), ('RU-PNZ', 'Пензенская область'), ('RU-PSK', 'Псковская область'), ('RU-ROS', 'Ростовская область'), ('RU-RYA', 'Рязанская область'), ('RU-SAM', 'Самарская область'), ('RU-SAR', 'Саратовская область'), ('RU-SAK', 'Сахалинская область'), ('RU-SVE', 'Свердловская область'), ('RU-SMO', 'Смоленская область'), ('RU-TAM', 'Тамбовская область'), ('RU-TVE', 'Тверская область'), ('RU-TOM', 'Томская область'), ('RU-TUL', 'Тульская область'), ('RU-TYU', 'Тюменская область'), ('RU-ULY', 'Ульяновская область'), ('RU-CHE', 'Челябинская область'), ('RU-YAR', 'Ярославская область'), ('RU-AD', 'Республика Адыгея'), ('RU-BA', 'Республика Башкортостан'), ('RU-BU', 'Республика Бурятия'), ('RU-DA', 'Республика Дагестан'), ('RU-IN', 'Республика Ингушетия'), ('RU-KB', 'Кабардино-Балкарская Республика'), ('RU-KL', 'Республика Калмыкия'), ('RU-KC', 'Карачаево-Черкесская Республика'), ('RU-KR', 'Республика Карелия'), ('UA-43', 'Республика Крым'), ('RU-ME', 'Республика Марий Эл'), ('RU-MO', 'Республика Мордовия'), ('RU-AL', 'Республика Алтай'), ('RU-KO', 'Республика Коми'), ('RU-SA', 'Республика Саха (Якутия)'), ('RU-SE', 'Республика Северная Осетия — Алания'), ('RU-TA', 'Республика Татарстан'), ('RU-TY', 'Республика Тыва'), ('RU-UD', 'Удмуртская Республика'), ('RU-KK', 'Республика Хакасия'), ('RU-CE', 'Чеченская Республика'), ('RU-CU', 'Чувашская Республика'), ('RU-ALT', 'Алтайский край'), ('RU-ZAB', 'Забайкальский край'), ('RU-KAM', 'Камчатский край'), ('RU-KDA', 'Краснодарский край'), ('RU-KYA', 'Красноярский край'), ('RU-PER', 'Пермский край'), ('RU-PRI', 'Приморский край'), ('RU-STA', 'Ставропольский край'), ('RU-KHA', 'Хабаровский край'), ('RU-NEN', 'Ненецкий автономный округ'), ('RU-KHM', 'Ханты-Мансийский автономный округ — Югра'), ('RU-CHU', 'Чукотский автономный округ'), ('RU-YAN', 'Ямало-Ненецкий автономный округ'), ('RU-YEV', 'Еврейская автономная область'), ('RU-SPE', 'Санкт-Петербург'), ('RU-MOW', 'Москва'), ('UA-40', 'Севастополь')], default='RU', max_length=16, verbose_name='Регион')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество ограничений')),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, default='', null=True), blank=True, null=True, size=None)),
                ('public_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Публичное название')),
                ('public_description', models.TextField(blank=True, null=True, verbose_name='Публичное описание')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, назначенный на заявку')),
                ('duplicate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='core.mediaincident', verbose_name='Дубликат')),
                ('incident_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.incidenttype')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='core.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Инцидент из СМИ',
                'verbose_name_plural': 'Инциденты из СМИ',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='incident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='core.mediaincident', verbose_name='Инцидент'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.source', verbose_name='Источник'),
        ),
    ]
