# Generated by Django 2.2.5 on 2020-02-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaincident',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='userincident',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок'),
        ),
    ]
