# Generated by Django 3.0.3 on 2020-03-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200220_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userincident',
            old_name='email',
            new_name='applicant_email',
        ),
        migrations.AddField(
            model_name='userincident',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя заявителя'),
        ),
    ]
