# Generated by Django 3.0.3 on 2020-03-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200312_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaincident',
            name='incident_type',
            field=models.IntegerField(default=0, verbose_name='Вид ограничения'),
        ),
        migrations.AlterField(
            model_name='userincident',
            name='incident_type',
            field=models.IntegerField(default=0, verbose_name='Вид ограничения'),
        ),
    ]
