# Generated by Django 3.0.3 on 2020-03-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userincident_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaincident',
            name='public_applicant_name',
        ),
    ]
