# Generated by Django 3.2.21 on 2024-05-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(choices=[('ALL', 'Все страны из списка'), ('ARM', 'Армения'), ('AZE', 'Азербайджан'), ('BLR', 'Беларусь'), ('EST', 'Эстония'), ('GEO', 'Грузия'), ('KAZ', 'Казахстан'), ('KGZ', 'Киргизия'), ('LVA', 'Латвия'), ('LTU', 'Литва'), ('MDA', 'Молдова'), ('RUS', 'Россия'), ('TJK', 'Таджикистан'), ('TKM', 'Туркменистан'), ('UKR', 'Украина'), ('UZB', 'Узбекистан'), ('DEU', 'Германия')], default='ALL', max_length=100, verbose_name='Страна'),
        ),
    ]
