# Generated by Django 3.0.3 on 2020-03-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_mediaincident_public_applicant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaincident',
            name='public_organization',
        ),
        migrations.RemoveField(
            model_name='userincident',
            name='public_organization',
        ),
    ]
