# Generated by Django 3.2.21 on 2024-05-27 23:17

from django.db import migrations, models
import django.db.models.deletion
import server.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240527_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='country',
            field=models.ForeignKey(blank=True, default=server.apps.core.models.get_default_country_id, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
    ]
