# Generated by Django 3.2.21 on 2024-08-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240819_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaincident',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
