# Generated by Django 3.2.21 on 2024-05-27 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_source_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
    ]
