# Generated by Django 3.2.21 on 2024-08-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mediaincident_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_tg_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрытый канал в телеграме'),
        ),
    ]
