# Generated by Django 3.0.5 on 2020-04-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_campaign_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL списка новостей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.AlterField(
            model_name='mediaincident',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не обработана'), (1, 'Обработана и отклонена'), (2, 'Обработана и принята'), (3, 'Коммуникации'), (4, 'В работе'), (5, 'Выполнена')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userincident',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не обработана'), (1, 'Обработана и отклонена'), (2, 'Обработана и принята'), (3, 'Коммуникации'), (4, 'В работе'), (5, 'Выполнена')], default=0, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('title', models.TextField(default='', verbose_name='Заголовок')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('is_downloaded', models.BooleanField(default=False, verbose_name='Скачана')),
                ('relevance', models.IntegerField(null=True, verbose_name='Оценка релевантности')),
                ('incident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.MediaIncident', verbose_name='Инцидент')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='core.Source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Cтатья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
