# Generated by Django 3.2.21 on 2024-09-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240904_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=1024, primary_key=True, serialize=False, verbose_name='URL'),
        ),
    ]
