# Generated by Django 3.2.21 on 2024-05-29 23:28

from django.db import migrations, models
import django.db.models.deletion
import server.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_source_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(choices=[('ALL', 'Все страны из списка'), ('ARM', 'Армения'), ('AZE', 'Азербайджан'), ('BLR', 'Беларусь'), ('EST', 'Эстония'), ('GEO', 'Грузия'), ('KAZ', 'Казахстан'), ('KGZ', 'Киргизия'), ('LVA', 'Латвия'), ('LTU', 'Литва'), ('MDA', 'Молдова'), ('RUS', 'Россия'), ('TJK', 'Таджикистан'), ('TKM', 'Туркменистан'), ('UKR', 'Украина'), ('UZB', 'Узбекистан'), ('DEU', 'Германия')], default='RUS', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='source',
            name='country',
            field=models.ForeignKey(default=server.apps.core.models.get_default_country_id, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
    ]
