# Generated by Django 3.0.5 on 2020-04-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200421_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_incident_created',
            field=models.BooleanField(default=False, verbose_name='Инцидент создан'),
        ),
    ]
