# Generated by Django 3.2.21 on 2024-09-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaincident',
            name='downvote',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Downvoted'),
        ),
    ]
