# Generated by Django 3.2.21 on 2024-10-09 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240922_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='login',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Порт'),
        ),
    ]
