# Generated by Django 3.0.5 on 2020-04-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_article_is_incident_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='mediaincident',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не обработан'), (1, 'Обработан и отклонен'), (2, 'Обработан и принят'), (3, 'Коммуникации'), (4, 'В работе'), (5, 'Выполнен')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userincident',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не обработан'), (1, 'Обработан и отклонен'), (2, 'Обработан и принят'), (3, 'Коммуникации'), (4, 'В работе'), (5, 'Выполнен')], default=0, verbose_name='Статус'),
        ),
    ]
