# Generated by Django 3.0.5 on 2020-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200428_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.TextField(unique=True, verbose_name='URL списка новостей'),
        ),
    ]
