# Generated by Django 3.2.21 on 2024-09-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20240922_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaincident",
            name="downvote",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="Downvoted"
            ),
        ),
    ]
