# Generated by Django 3.2.21 on 2024-10-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_mediaincident_downvote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="duplicate_url",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="Дубликат чего"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="redirect_url",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="Редирект куда"
            ),
        ),
    ]
