# Generated by Django 3.0.6 on 2020-05-20 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaincident',
            name='create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userincident',
            name='create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
    ]
