# Generated by Django 3.2.21 on 2024-11-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20241022_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="is_tg_hidden",
            field=models.BooleanField(
                default=False, verbose_name="Скрытый канал в телеграме"
            ),
        ),
    ]
