# Generated by Django 3.2.21 on 2024-11-01 00:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20241022_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='needs_proxy',
            field=models.BooleanField(default=False, verbose_name='Требуется прокси'),
        ),
        migrations.AlterField(
            model_name='source',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', unique=True, validators=[django.core.validators.validate_ipv4_address], verbose_name='IP адрес')),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Порт')),
                ('login', models.CharField(blank=True, max_length=128, null=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
                'ordering': ['country', 'ip', 'port'],
                'unique_together': {('ip', 'port')},
            },
        ),
    ]
