# Generated by Django 3.0.6 on 2020-06-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lead_text',
            field=models.TextField(default='', verbose_name='Текст на карточке'),
            preserve_default=False,
        ),
    ]
