# Generated by Django 3.2.21 on 2025-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20250119_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='error_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
