# Generated by Django 3.2.21 on 2025-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20250120_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='error_message',
        ),
        migrations.AlterField(
            model_name='proxy',
            name='error_type',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип ошибки'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='last_check',
            field=models.DateTimeField(null=True, verbose_name='Последняя проверка'),
        ),
    ]
