# Generated by Django 3.0.6 on 2020-06-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_post_lead_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='card_type',
            field=models.IntegerField(choices=[(0, 'По умолчанию (только название)'), (1, 'Название на фоне изображения'), (2, 'Название, изображение и описание')], default=0, verbose_name='Тип карточки'),
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(blank=True, choices=[('#375ABB', 'Синий «Azure»'), ('#1B1F3B', 'Темный «Mirage»'), ('#FB8F8A', 'Светлый «Geraldine»')], default='#375ABB', max_length=12, null=True, verbose_name='Цвет карточки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lead_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст на карточке'),
        ),
        migrations.RenameField(
            model_name='post',
            old_name='lead_text',
            new_name='card_text',
        ),
    ]
