# Generated by Django 3.0.6 on 2020-06-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200618_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaincident',
            name='incident_type',
            field=models.IntegerField(choices=[(1, 'Уголовное преследование'), (2, 'Административное давление'), (3, 'Запрет информации'), (4, 'Регулирование'), (5, 'Насилие'), (6, 'Ограничение доступа'), (7, 'Гражданские иски'), (8, 'Кибератака'), (0, 'Другое')], default=0, verbose_name='Вид ограничения'),
        ),
        migrations.AlterField(
            model_name='userincident',
            name='incident_type',
            field=models.IntegerField(choices=[(1, 'Уголовное преследование'), (2, 'Административное давление'), (3, 'Запрет информации'), (4, 'Регулирование'), (5, 'Насилие'), (6, 'Ограничение доступа'), (7, 'Гражданские иски'), (8, 'Кибератака'), (0, 'Другое')], default=0, verbose_name='Вид ограничения'),
        ),
        migrations.CreateModel(
            name='UserIncidentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.UserIncident')),
            ],
            options={
                'verbose_name': 'Файлы инцидентов по заявкам',
                'verbose_name_plural': 'Файл инцидента по заявке',
            },
        ),
        migrations.CreateModel(
            name='MediaIncidentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.MediaIncident')),
            ],
            options={
                'verbose_name': 'Файлы инцидентов из СМИ',
                'verbose_name_plural': 'Файл инцидента из СМИ',
            },
        ),
    ]
