# Generated by Django 3.2.21 on 2025-01-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20250128_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
    ]
