# Generated by Django 3.2.21 on 2025-01-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_is_tg_hidden_flag'),
        ('core', '0021_auto_20250128_0825'),
    ]

    operations = [
    ]
