# Generated by Django 3.0.6 on 2020-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200707_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='algorithm',
            field=models.CharField(choices=[('marker', 'По маркерам'), ('cosine', 'Косинусные расстояния')], default='cosine', max_length=6, verbose_name='Алгоритм оценки'),
        ),
    ]
