# Generated by Django 3.0.9 on 2020-08-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_source_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userincident',
            name='applicant_email',
            field=models.CharField(max_length=128, verbose_name='Email или мессенджер'),
        ),
    ]
