# Generated by Django 3.1 on 2020-08-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200805_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='form_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Форма в JSON'),
        ),
        migrations.AlterField(
            model_name='userincident',
            name='form_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные из формы'),
        ),
    ]
