# Generated by Django 3.2.21 on 2025-03-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20250308_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='name',
            new_name='public_tg_channel_link',
        ),
        migrations.RemoveField(
            model_name='source',
            name='is_tg_hidden',
        ),
        migrations.AddField(
            model_name='source',
            name='is_telethon',
            field=models.BooleanField(default=False, verbose_name='Парсинг через телетон'),
        ),
    ]
