# Generated by Django 3.1 on 2020-08-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200819_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaincident',
            name='duplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediaincident', verbose_name='Дубликат'),
        ),
        migrations.AlterField(
            model_name='mediaincident',
            name='incident_type',
            field=models.IntegerField(choices=[(1, 'Уголовное преследование'), (2, 'Административное давление'), (3, 'Запрет информации'), (4, 'Регулирование'), (5, 'Насилие'), (6, 'Ограничение доступа'), (7, 'Гражданские иски'), (8, 'Кибератаки'), (0, 'Другое')], default=0, verbose_name='Вид ограничения'),
        ),
        migrations.AlterField(
            model_name='userincident',
            name='incident_type',
            field=models.IntegerField(choices=[(1, 'Уголовное преследование'), (2, 'Административное давление'), (3, 'Запрет информации'), (4, 'Регулирование'), (5, 'Насилие'), (6, 'Ограничение доступа'), (7, 'Гражданские иски'), (8, 'Кибератаки'), (0, 'Другое')], default=0, verbose_name='Вид ограничения'),
        ),
    ]
