# Generated by Django 3.1.3 on 2020-11-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20201124_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='description',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='stage',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.campaign', verbose_name='Кампания'),
        ),
    ]
