# Generated by Django 3.1.3 on 2020-11-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201124_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
