# Generated by Django 3.1.3 on 2020-11-25 21:26

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    UserIncident = apps.get_model('core', 'UserIncident')
    for row in UserIncident.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_userincident_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
