# Generated by Django 3.1.3 on 2020-11-25 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userincident',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
