# Generated by Django 3.1.3 on 2020-12-01 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_uuid_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(verbose_name='Текст')),
                ('instruction', models.TextField(blank=True, default='', verbose_name='Инструкция')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='core.campaign', verbose_name='Кампания')),
            ],
        ),
        migrations.DeleteModel(
            name='DocGenerator',
        ),
    ]
