# Generated by Django 3.1.3 on 2020-12-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20201216_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='chart_field',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Поле для диаграммы'),
        ),
    ]
