# Generated by Django 3.1.3 on 2020-12-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_campaign_chart_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userincident',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userincident',
            name='applicant_email',
            field=models.CharField(max_length=128, verbose_name='Email, телефон или мессенджер'),
        ),
    ]
