# Generated by Django 3.1.3 on 2020-12-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20201220_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(blank=True, default='', verbose_name='URL'),
        ),
    ]
