# Generated by Django 3.1.3 on 2020-12-26 13:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20201222_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='terms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=32, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='incident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='core.mediaincident', verbose_name='Инцидент'),
        ),
    ]
