# Generated by Django 3.1.4 on 2020-12-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201226_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='chart_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пояснение диаграммы'),
        ),
    ]
