# Generated by Django 3.1.4 on 2021-01-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_campaign_chart_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaincident',
            name='incident_type',
            field=models.IntegerField(choices=[(1, 'Уголовное преследование'), (2, 'Административное давление'), (4, 'Регулирование'), (5, 'Насилие'), (6, 'Интернет-цензура'), (7, 'Гражданские иски'), (8, 'Кибератаки'), (9, 'Давление на IT-бизнес'), (10, 'Шатдауны'), (0, 'Другое')], default=0, verbose_name='Вид ограничения'),
        ),
        migrations.AlterField(
            model_name='userincident',
            name='incident_type',
            field=models.IntegerField(choices=[(1, 'Уголовное преследование'), (2, 'Административное давление'), (4, 'Регулирование'), (5, 'Насилие'), (6, 'Интернет-цензура'), (7, 'Гражданские иски'), (8, 'Кибератаки'), (9, 'Давление на IT-бизнес'), (10, 'Шатдауны'), (0, 'Другое')], default=0, verbose_name='Вид ограничения'),
        ),
    ]
