# Generated by Django 3.1.4 on 2021-01-29 09:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210123_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='markers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32, null=True), blank=True, null=True, size=None, verbose_name='Маркеры в тексте'),
        ),
    ]
