# Generated by Django 3.2 on 2021-04-27 08:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20210302_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
