# Generated by Django 3.2 on 2021-04-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_campaign_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='applicant_name_required',
            field=models.BooleanField(default=True, verbose_name='Спрашивать имя'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description_required',
            field=models.BooleanField(default=True, verbose_name='Спрашивать описание'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='files_required',
            field=models.BooleanField(default=True, verbose_name='Спрашивать файлы'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='form_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок формы'),
        ),
    ]
