# Generated by Django 3.2 on 2021-05-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210427_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='notify_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email для оповещений'),
        ),
    ]
