# Generated by Django 3.2 on 2021-05-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_campaign_notify_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='applicant_name_required',
        ),
        migrations.RemoveField(
            model_name='userincident',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='userincident',
            name='public_applicant_name',
        ),
        migrations.AddField(
            model_name='campaign',
            name='applicant_messenger_required',
            field=models.BooleanField(default=True, verbose_name='Спрашивать мессенджер'),
        ),
        migrations.AddField(
            model_name='userincident',
            name='applicant_messenger',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Аккаунт в мессенджере'),
        ),
        migrations.AlterField(
            model_name='userincident',
            name='applicant_email',
            field=models.CharField(max_length=128, verbose_name='Email'),
        ),
    ]
