# Generated by Django 3.2 on 2021-05-25 14:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210520_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='reply_email_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка ответного письма'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reply_email_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст ответного письма'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_reply_email',
            field=models.BooleanField(default=False, verbose_name='Отправлять ответное письмо'),
        ),
    ]
