# Generated by Django 3.2 on 2021-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20210525_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='applicant_region_required',
            field=models.BooleanField(default=False, verbose_name='Спрашивать регион'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='applicant_messenger_required',
            field=models.BooleanField(default=False, verbose_name='Спрашивать мессенджер'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description_required',
            field=models.BooleanField(default=False, verbose_name='Спрашивать описание'),
        ),
    ]
