# Generated by Django 3.2 on 2021-05-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20210525_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='background',
        ),
        migrations.AddField(
            model_name='campaign',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Основной цвет'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_background',
            field=models.BooleanField(default=True, verbose_name='Использовать как фон'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение кампании'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='submit_button_text',
            field=models.CharField(blank=True, default='Отправить', max_length=128, verbose_name='Текст на кнопке'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Основной цвет'),
        ),
    ]
