# Generated by Django 3.2 on 2021-05-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20210528_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('emphasized', models.BooleanField(default=False, verbose_name='Выделенный')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='core.campaign', verbose_name='Кампания')),
            ],
        ),
    ]
