# Generated by Django 3.2 on 2021-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет текста'),
        ),
    ]
