# Generated by Django 3.2 on 2021-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20210528_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='form_description',
            field=models.TextField(blank=True, default='', verbose_name='Пояснение в форме'),
        ),
    ]
