# Generated by Django 3.2 on 2021-06-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_campaign_form_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='thanks_header',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='thanks_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст спасибо-страницы'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='use_custom_thanks',
            field=models.BooleanField(default=False, verbose_name='Показывать свой текст спасибо-страницы'),
        ),
    ]
