# Generated by Django 3.2 on 2021-06-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20210602_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='Название в URL')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.campaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Доп.страница',
                'verbose_name_plural': 'Доп.страницы',
            },
        ),
    ]
