# Generated by Django 3.2 on 2021-11-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_stage_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Запрещенная на территории РФ организация'),
        ),
    ]
