# Generated by Django 3.2.12 on 2022-02-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0057_add_banned_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaincident',
            name='incident_type',
            field=models.IntegerField(
                choices=[(1, 'Уголовное преследование'), (2, 'Административное давление'), (4, 'Регулирование'),
                         (5, 'Насилие'), (6, 'Интернет-цензура'), (7, 'Гражданские иски'), (8, 'Кибератаки'),
                         (9, 'Давление на IT-бизнес'), (10, 'Шатдауны'),
                         (11, 'Запросы личной информации у интернет-сервисов'), (0, 'Другое')], default=0,
                verbose_name='Вид ограничения'),
        ),
        migrations.AlterField(
            model_name='userincident',
            name='incident_type',
            field=models.IntegerField(
                choices=[(1, 'Уголовное преследование'), (2, 'Административное давление'), (4, 'Регулирование'),
                         (5, 'Насилие'), (6, 'Интернет-цензура'), (7, 'Гражданские иски'), (8, 'Кибератаки'),
                         (9, 'Давление на IT-бизнес'), (10, 'Шатдауны'),
                         (11, 'Запросы личной информации у интернет-сервисов'), (0, 'Другое')], default=0,
                verbose_name='Вид ограничения'),
        ),
    ]
