# Generated by Django 3.2.12 on 2022-06-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0058_change_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLeak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=12)),
                ('data', models.JSONField()),
            ],
        ),
    ]
