# Generated by Django 3.2.12 on 2023-08-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_dataleaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_duplicate',
            field=models.BooleanField(default=False, verbose_name='Дубликат'),
        ),
    ]
