# Generated by Django 3.2.12 on 2023-07-18 19:26

from django.db import migrations, models
import django.db.models.deletion
import pathlib


def create_incident_types(apps, schema_editor):
    IncidentType = apps.get_model('core', 'IncidentType')
    INCIDENT_TYPES = [
        'Уголовное преследование',
        'Административное давление',
        'Регулирование',
        'Насилие',
        'Интернет-цензура',
        'Гражданские иски',
        'Кибератаки',
        'Давление на IT-бизнес',
        'Шатдауны',
        'Запросы личной информации у интернет-сервисов',
        'Другое',
    ]
    for desc in INCIDENT_TYPES:
        IncidentType.objects.create(description=desc)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20230718_1925'),
    ]

    operations = [
        migrations.RunPython(create_incident_types),
    ]
