# Generated by Django 3.2.12 on 2023-08-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_incidenttype_treshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignpage',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='document',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='explanation',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='userincident',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='CampaignPage',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
