# Generated by Django 3.2.12 on 2023-08-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20230822_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataLeak',
        ),
    ]
