# Generated by Django 3.2.12 on 2023-08-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_delete_dataleak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
