# Generated by Django 3.2.12 on 2023-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_delete_dataleak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenttype',
            name='zip_file',
        ),
        migrations.AddField(
            model_name='incidenttype',
            name='model_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
