# Generated by Django 3.2.12 on 2023-08-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_delete_post'),
        ('core', '0066_delete_stage'),
    ]

    operations = [
    ]
