# Generated by Django 3.2.12 on 2023-08-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_merge_0066_delete_post_0066_delete_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Explanation',
        ),
    ]
