# Generated by Django 3.2.12 on 2023-09-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_delete_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Explanation',
        ),
        migrations.RemoveField(
            model_name='userincidentfile',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='incidenttype',
            name='zip_file',
        ),
        migrations.AddField(
            model_name='incidenttype',
            name='model_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MediaIncidentFile',
        ),
        migrations.DeleteModel(
            name='UserIncidentFile',
        ),
    ]
