# Generated by Django 3.2.12 on 2023-09-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20230907_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='mediaincident',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='userincident',
            name='tags',
        ),
    ]
