# Generated by Django 3.2.12 on 2023-09-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20230907_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserIncident',
        ),
    ]
