# Generated by Django 3.2.21 on 2023-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_delete_userincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttype',
            name='chat_gpt_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Chat-GPR промпт'),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название модели'),
        ),
    ]
