# Generated by Django 3.2.21 on 2023-09-28 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20230922_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(blank=True, default='', primary_key=True, serialize=False, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='mediaincident',
            name='incident_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.incidenttype'),
        ),
    ]
