# Generated by Django 3.2.21 on 2023-10-05 11:50

from django.db import migrations, models
from datetime import datetime, timedelta


# all articles that downloaded and publication date at least 1 day old should be already parsed
def update_field(apps, schema_editor):
    start_date = datetime.now().date() - timedelta(days=1)

    Article = apps.get_model('core', 'Article')
    arts = Article.objects.filter(is_downloaded=True, publication_date__lte=start_date)
    for art in arts:
        art.is_parsed = True
        art.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20230928_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_parsed',
            field=models.BooleanField(default=False, verbose_name='Обработана'),
        ),
        migrations.RunPython(update_field),
    ]
