# Generated by Django 3.2.21 on 2023-10-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_article_is_parsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='terms',
        ),
    ]
