# Generated by Django 3.2.21 on 2023-10-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_article_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttype',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
