# Generated by Django 3.2.21 on 2023-10-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_incidenttype_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='relevance',
        ),
        migrations.AddField(
            model_name='article',
            name='rate',
            field=models.JSONField(blank=True, null=True, verbose_name='Оценка релевантности'),
        ),
    ]
