# Generated by Django 3.2.21 on 2023-10-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20231016_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rate',
            field=models.JSONField(default={}, verbose_name='Оценка релевантности'),
        ),
    ]
