# Generated by Django 3.2.21 on 2023-10-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_article_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rate',
            field=models.JSONField(default=dict, verbose_name='Оценка релевантности'),
        ),
    ]
