# Generated by Django 3.2.21 on 2023-10-24 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_article_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaincident',
            name='related_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='core.article', verbose_name='Статья'),
        ),
    ]
