# Generated by Django 3.2.21 on 2023-10-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_mediaincident_related_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenttype',
            name='treshold',
            field=models.FloatField(default=1, verbose_name='Treshold для модели'),
        ),
    ]
