# Generated by Django 2.2.4 on 2019-09-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_logo_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
