# Generated by Django 3.0.3 on 2020-03-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200320_1322'),
        ('users', '0003_add_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organizations',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
