# Generated by Django 3.2.21 on 2023-09-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=32, unique=True)),
                ('cat_01', models.BooleanField(default=True, verbose_name='Увольнения')),
                ('cat_02', models.BooleanField(default=True, verbose_name='Забастовки')),
                ('cat_03', models.BooleanField(default=True, verbose_name='Диверсии')),
            ],
        ),
    ]
