# Generated by Django 3.2.21 on 2023-09-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20230907_0856'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='cat_01',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='cat_02',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='cat_03',
        ),
        migrations.CreateModel(
            name='TypeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.channel')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.incidenttype')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='type',
            field=models.ManyToManyField(through='bot.TypeStatus', to='core.IncidentType'),
        ),
    ]
