# Generated by Django 3.2.21 on 2024-06-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20240611_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionstatus',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='regionstatus',
            name='region',
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='region',
        ),
        migrations.DeleteModel(
            name='CountryStatus',
        ),
        migrations.DeleteModel(
            name='RegionStatus',
        ),
    ]
