# Generated by Django 3.2.21 on 2024-09-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20240710_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelincidenttype',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
