# Generated by Django 3.2.21 on 2024-07-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20240710_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelincidenttype',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
    ]
