name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - stage
  workflow_dispatch:
    inputs:
      runType:
        description: "How to run this build?"
        required: true
        default: "default"
        type: choice
        options:
          - Force build
          - Default

jobs:
  clean:
    name: Clean images
    runs-on: ["self-hosted", "neuroparser", "${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}"]
    steps:
      - name: Clean unused images and network
        run: |
          docker image prune -f

  build:
    name: Build
    needs:
      - clean
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      runType: "${{ github.event.inputs.runType }}"

  test:
    name: Run tests
    needs:
      - build
    uses: "./.github/workflows/tests.web.yml"
    secrets: inherit

  start_staging:
    name: Start staging
    needs:
      - test
      - build
    uses: "./.github/workflows/deploy.yml"
    if: success()
    # if: success() && github.ref == 'refs/heads/stage'
    secrets: inherit
    with:
      runner: staging
      environment: Staging

      env_telegram_bot_name: "${{ vars.TELEGRAM_BOT_NAME_STAGE }}"
      env_telegram_bot_url: "${{ vars.TELEGRAM_BOT_URL_STAGE}}"
      env_flower_host: "${{ vars.FLOWER_HOST }}"
      env_host: "${{ vars.HOST_STAGE }}"

  start_prod:
    name: Start prod
    needs:
      - test
      - build
    uses: "./.github/workflows/deploy.yml"
    if: success() && github.ref == 'refs/heads/main'
    secrets: inherit
    with:
      runner: production
      environment: Production
    
      env_telegram_bot_name: "${{ vars.TELEGRAM_BOT_NAME }}"
      env_telegram_bot_url: "${{ vars.TELEGRAM_BOT_URL }}"
      env_flower_host: "${{ vars.FLOWER_HOST }}"
      env_host: "${{ vars.HOST }}"
