name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - stage
  workflow_dispatch:
    inputs:
      runType:
        description: "How to run this build?"
        required: true
        default: "default"
        type: choice
        options:
          - Force build
          - Default
      keepTests:
        description: "Keep test artifacts and folders. They will be kept only in case of failed tests by default"
        required: true
        default: "default"
        type: choice
        options:
          - Always keep
          - Default

jobs:
  clean:
    name: Clean images
    runs-on: ["self-hosted", "neuroparser", "${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}"]
    steps:
      - name: Clean unused images and network
        run: |
          docker image prune -f

  build:
    name: Build
    needs:
      - clean
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      runType: "${{ github.event.inputs.runType }}"

  test:
    name: Run tests
    needs:
      - build
    uses: "./.github/workflows/tests.web.yml"
    secrets: inherit
    with:
      keepTests: "${{ github.event.inputs.keepTests == 'Always keep'}}"

  start_staging:
    name: Start staging
    needs:
      - test
      - build
    uses: "./.github/workflows/deploy.yml"
    if: success() && github.ref == 'refs/heads/stage'
    secrets: inherit
    with:
      environment: staging

  start_prod:
    name: Start prod
    needs:
      - test
      - build
    uses: "./.github/workflows/deploy.yml"
    if: success() && github.ref == 'refs/heads/main'
    secrets: inherit
    with:
      environment: production
